on:
  push:
  pull_request:

name: CI
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install and build
        run: |
          npm ci
          npm run minify
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pages
          path: dist/

  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          ref: pages
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: pages
          path: .
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Deploy website."
